// apps/vue/src/App.vue

<template>
  <div>

    <div id="app">
        <ParcelPage />
      <img alt="Vue logo" src="./assets/logo.png">
      <br>

      <button @click="increment">+1</button>
      <HelloWorld msg="Welcome to Your Vue.js v3 App" />

    </div>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'
import ParcelPage from './components/ParcelPage.vue'
import {getState} from "@org/root-config";

export default {
  name: 'App',
  components: {
    HelloWorld,
    ParcelPage
},
methods: {
  increment() {
    getState().increment();
  }
}
}
</script>

<style>
#app{
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 10px;
  border: 4px dashed green;
}
#app > button{
  font-size: xx-large;
}

</style>

// apps/svelte/src/App.svelte
<script>
  export let name;
</script>

<div id="app">
  <img
    src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/498px-Svelte_Logo.svg.png?20191219133350"
    alt=""
    width="100px"
  />
  <h1>Hello Svelte!</h1>
  <section>{name} is mounted!!</section>
</div>

<style>
  #app {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 10px;
  }

  section {
    font-size: 1.5rem;
  }
</style>
